# Generated by Django 2.1.7 on 2019-09-10 15:05

import core.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItemsPricelist',
            fields=[
                ('id', models.AutoField(db_column='PLItemID', primary_key=True, serialize=False)),
                ('item_name', models.CharField(db_column='PLItemName', max_length=100)),
                ('pricelist_date', core.fields.DateField(db_column='DatePL')),
                ('validity_from', core.fields.DateTimeField(db_column='ValidityFrom')),
                ('validity_to', core.fields.DateTimeField(blank=True, db_column='ValidityTo', null=True)),
                ('legacy_id', models.IntegerField(blank=True, db_column='LegacyID', null=True)),
                ('audit_user_id', models.IntegerField(db_column='AuditUserID')),
            ],
            options={
                'db_table': 'tblPLItems',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ItemsPricelistDetail',
            fields=[
                ('id', models.AutoField(db_column='PLItemDetailID', primary_key=True, serialize=False)),
                ('price_overrule', models.DecimalField(blank=True, db_column='PriceOverule', decimal_places=2, max_digits=18, null=True)),
                ('validity_from', core.fields.DateTimeField(db_column='ValidityFrom')),
                ('validity_to', core.fields.DateTimeField(blank=True, db_column='ValidityTo', null=True)),
                ('legacy_id', models.IntegerField(blank=True, db_column='LegacyID', null=True)),
                ('audit_user_id', models.IntegerField(db_column='AuditUserID')),
            ],
            options={
                'db_table': 'tblPLItemsDetail',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ServicesPricelist',
            fields=[
                ('id', models.AutoField(db_column='PLServiceID', primary_key=True, serialize=False)),
                ('service_name', models.CharField(db_column='PLServName', max_length=100)),
                ('pricelist_date', core.fields.DateField(db_column='DatePL')),
                ('validity_from', core.fields.DateTimeField(db_column='ValidityFrom')),
                ('validity_to', core.fields.DateTimeField(blank=True, db_column='ValidityTo', null=True)),
                ('legacy_id', models.IntegerField(blank=True, db_column='LegacyID', null=True)),
                ('audit_user_id', models.IntegerField(db_column='AuditUserID')),
            ],
            options={
                'db_table': 'tblPLServices',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ServicesPricelistDetail',
            fields=[
                ('id', models.AutoField(db_column='PLServiceDetailID', primary_key=True, serialize=False)),
                ('price_overrule', models.DecimalField(blank=True, db_column='PriceOverule', decimal_places=2, max_digits=18, null=True)),
                ('validity_from', core.fields.DateTimeField(db_column='ValidityFrom')),
                ('validity_to', core.fields.DateTimeField(blank=True, db_column='ValidityTo', null=True)),
                ('legacy_id', models.IntegerField(blank=True, db_column='LegacyID', null=True)),
                ('audit_user_id', models.IntegerField(db_column='AuditUserID')),
            ],
            options={
                'db_table': 'tblPLServicesDetail',
                'managed': False,
            },
        ),
    ]
