# Generated by Django 3.2.18 on 2023-05-12 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medical_pricelist', '0003_update_django_scheme'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemspricelist',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='itemspricelistdetail',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='servicespricelist',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='servicespricelistdetail',
            options={'managed': True},
        ),
    ]
